### ISSUE TITLE
Make Delayed Arrow Rendering block the particles produced for a few frames

### ISSUE THREAD

**Issue by MicrocontrollersDev** [Polyfrost/Easeify#3]
Currently, the Delayed Arrow Rendering feature does nothing. This was already added in vanilla Minecraft in 1.16 as can be seen [here](https://youtu.be/rcHiRdrsAfk?t=3607).

To make this feature have a use, it should block the rendering of the critical particles that spawn for a fully charged bow shot for a few frames, as this still spawns directly in front of the player's camera. [Gif representing the particles](https://cdn.discordapp.com/attachments/929901581296619543/977047567110127666/java_S10IxIKYcJ.gif)

**Comment by Wyvest** [comment]
don't think this is possible unless all crit particles are cancelled for 2 ticks
